# Consulte https://aka.ms/customizecontainer para aprender a personalizar su contenedor de depuración y cómo Visual Studio usa este Dockerfile para compilar sus imágenes para una depuración más rápida.

# Dependiendo del sistema operativo de las máquinas host que vayan a compilar o ejecutar los contenedores, puede que sea necesario cambiar la imagen especificada en la instrucción FROM.
# Para más información, consulte https://aka.ms/containercompat

# Esta fase se usa cuando se ejecuta desde VS en modo rápido (valor predeterminado para la configuración de depuración)
FROM mcr.microsoft.com/dotnet/runtime:10.0-nanoserver-ltsc2022 AS base
WORKDIR /app


# Esta fase se usa para compilar el proyecto de servicio
FROM mcr.microsoft.com/dotnet/sdk:10.0-windowsservercore-ltsc2022 AS build
# Instalación de Visual Studio Build Tools, necesarias para la publicación de aot
# Nota: El uso del Visual Studio Build Tools requiere una licencia de Visual Studio válida.
RUN curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe
RUN vs_buildtools.exe --installPath C:\BuildTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.19041 --quiet --wait --norestart --nocache
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Venta_de_combustible_Programa2Adalberto/Venta_de_combustible_Programa2Adalberto.csproj", "Venta_de_combustible_Programa2Adalberto/"]
RUN dotnet restore "./Venta_de_combustible_Programa2Adalberto/Venta_de_combustible_Programa2Adalberto.csproj"
COPY . .
WORKDIR "/src/Venta_de_combustible_Programa2Adalberto"
RUN dotnet build "./Venta_de_combustible_Programa2Adalberto.csproj" -c %BUILD_CONFIGURATION% -o /app/build

# Esta fase se usa para publicar el proyecto de servicio que se copiará en la fase final.
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Venta_de_combustible_Programa2Adalberto.csproj" -c %BUILD_CONFIGURATION% -o /app/publish /p:UseAppHost=true

# Esta fase se usa en producción o cuando se ejecuta desde VS en modo normal (valor predeterminado cuando no se usa la configuración de depuración)
FROM mcr.microsoft.com/dotnet/runtime:10.0-nanoserver-ltsc2022 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["Venta_de_combustible_Programa2Adalberto.exe"]