#nullable disable
namespace AgenteProblemaWinForms
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            rootLayout = new System.Windows.Forms.TableLayoutPanel();
            headerPanel = new System.Windows.Forms.Panel();
            lblTitulo = new System.Windows.Forms.Label();
            lblSubtitulo = new System.Windows.Forms.Label();
            lblSesion = new System.Windows.Forms.Label();
            bodyLayout = new System.Windows.Forms.TableLayoutPanel();
            configPanel = new System.Windows.Forms.Panel();
            lblConfiguracion = new System.Windows.Forms.Label();
            lblProveedor = new System.Windows.Forms.Label();
            cmbProveedor = new System.Windows.Forms.ComboBox();
            lblModelo = new System.Windows.Forms.Label();
            txtModelo = new System.Windows.Forms.TextBox();
            lblNombre = new System.Windows.Forms.Label();
            txtNombre = new System.Windows.Forms.TextBox();
            lblProblema = new System.Windows.Forms.Label();
            txtProblema = new System.Windows.Forms.TextBox();
            lblInstrucciones = new System.Windows.Forms.Label();
            txtInstrucciones = new System.Windows.Forms.TextBox();
            btnCrear = new System.Windows.Forms.Button();
            btnNuevaSesion = new System.Windows.Forms.Button();
            lblClave = new System.Windows.Forms.Label();
            tabs = new System.Windows.Forms.TabControl();
            tabConversacion = new System.Windows.Forms.TabPage();
            tabHerramienta = new System.Windows.Forms.TabPage();
            tabConsumo = new System.Windows.Forms.TabPage();
            chatLayout = new System.Windows.Forms.TableLayoutPanel();
            lblChat = new System.Windows.Forms.Label();
            rtbConversacion = new System.Windows.Forms.RichTextBox();
            composer = new System.Windows.Forms.TableLayoutPanel();
            lblConsulta = new System.Windows.Forms.Label();
            txtConsulta = new System.Windows.Forms.TextBox();
            chatButtons = new System.Windows.Forms.FlowLayoutPanel();
            btnEnviar = new System.Windows.Forms.Button();
            btnCancelar = new System.Windows.Forms.Button();
            btnGuardar = new System.Windows.Forms.Button();
            lblToolInfo = new System.Windows.Forms.Label();
            dgvTareas = new System.Windows.Forms.DataGridView();
            colMateria = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPrioridad = new System.Windows.Forms.DataGridViewTextBoxColumn();
            btnAgregarTarea = new System.Windows.Forms.Button();
            btnQuitarTarea = new System.Windows.Forms.Button();
            lblMinutos = new System.Windows.Forms.Label();
            nudMinutos = new System.Windows.Forms.NumericUpDown();
            btnProbarHerramienta = new System.Windows.Forms.Button();
            lblHerramienta = new System.Windows.Forms.Label();
            txtEvidencia = new System.Windows.Forms.TextBox();
            lblConsumoInfo = new System.Windows.Forms.Label();
            lblTarifas = new System.Windows.Forms.Label();
            lblEntrada = new System.Windows.Forms.Label();
            lblSalida = new System.Windows.Forms.Label();
            nudTarifaEntrada = new System.Windows.Forms.NumericUpDown();
            nudTarifaSalida = new System.Windows.Forms.NumericUpDown();
            lblTokens = new System.Windows.Forms.Label();
            lblCosto = new System.Windows.Forms.Label();
            lblCostNote = new System.Windows.Forms.Label();
            lblEstado = new System.Windows.Forms.Label();
            rootLayout.SuspendLayout();
            headerPanel.SuspendLayout();
            bodyLayout.SuspendLayout();
            configPanel.SuspendLayout();
            tabs.SuspendLayout();
            tabConversacion.SuspendLayout();
            tabHerramienta.SuspendLayout();
            tabConsumo.SuspendLayout();
            chatLayout.SuspendLayout();
            composer.SuspendLayout();
            chatButtons.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvTareas).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudMinutos).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudTarifaEntrada).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudTarifaSalida).BeginInit();
            SuspendLayout();
            rootLayout.Name = "rootLayout";
            headerPanel.Name = "headerPanel";
            lblTitulo.Name = "lblTitulo";
            lblSubtitulo.Name = "lblSubtitulo";
            lblSesion.Name = "lblSesion";
            bodyLayout.Name = "bodyLayout";
            configPanel.Name = "configPanel";
            lblConfiguracion.Name = "lblConfiguracion";
            lblProveedor.Name = "lblProveedor";
            cmbProveedor.Name = "cmbProveedor";
            lblModelo.Name = "lblModelo";
            txtModelo.Name = "txtModelo";
            lblNombre.Name = "lblNombre";
            txtNombre.Name = "txtNombre";
            lblProblema.Name = "lblProblema";
            txtProblema.Name = "txtProblema";
            lblInstrucciones.Name = "lblInstrucciones";
            txtInstrucciones.Name = "txtInstrucciones";
            btnCrear.Name = "btnCrear";
            btnNuevaSesion.Name = "btnNuevaSesion";
            lblClave.Name = "lblClave";
            tabs.Name = "tabs";
            tabConversacion.Name = "tabConversacion";
            tabHerramienta.Name = "tabHerramienta";
            tabConsumo.Name = "tabConsumo";
            chatLayout.Name = "chatLayout";
            lblChat.Name = "lblChat";
            rtbConversacion.Name = "rtbConversacion";
            composer.Name = "composer";
            lblConsulta.Name = "lblConsulta";
            txtConsulta.Name = "txtConsulta";
            chatButtons.Name = "chatButtons";
            btnEnviar.Name = "btnEnviar";
            btnCancelar.Name = "btnCancelar";
            btnGuardar.Name = "btnGuardar";
            lblToolInfo.Name = "lblToolInfo";
            dgvTareas.Name = "dgvTareas";
            colMateria.Name = "colMateria";
            colPrioridad.Name = "colPrioridad";
            btnAgregarTarea.Name = "btnAgregarTarea";
            btnQuitarTarea.Name = "btnQuitarTarea";
            lblMinutos.Name = "lblMinutos";
            nudMinutos.Name = "nudMinutos";
            btnProbarHerramienta.Name = "btnProbarHerramienta";
            lblHerramienta.Name = "lblHerramienta";
            txtEvidencia.Name = "txtEvidencia";
            lblConsumoInfo.Name = "lblConsumoInfo";
            lblTarifas.Name = "lblTarifas";
            lblEntrada.Name = "lblEntrada";
            lblSalida.Name = "lblSalida";
            nudTarifaEntrada.Name = "nudTarifaEntrada";
            nudTarifaSalida.Name = "nudTarifaSalida";
            lblTokens.Name = "lblTokens";
            lblCosto.Name = "lblCosto";
            lblCostNote.Name = "lblCostNote";
            lblEstado.Name = "lblEstado";
            rootLayout.Dock = DockStyle.Fill;
            rootLayout.ColumnCount = 1;
            rootLayout.RowCount = 3;
            rootLayout.Margin = Padding.Empty;
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 88F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            headerPanel.Dock = DockStyle.Fill;
            headerPanel.BackColor = Color.FromArgb(26, 36, 62);
            headerPanel.Margin = Padding.Empty;
            lblTitulo.Location = new Point(24, 16);
            lblTitulo.Size = new Size(640, 36);
            lblTitulo.ForeColor = Color.FromArgb(44, 57, 83);
            lblTitulo.Text = "AULA / AGENTE DE ESTUDIO";
            lblTitulo.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblTitulo.Font = new Font("Segoe UI", 20F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.White;
            lblSubtitulo.Location = new Point(26, 57);
            lblSubtitulo.Size = new Size(760, 24);
            lblSubtitulo.ForeColor = Color.FromArgb(44, 57, 83);
            lblSubtitulo.Text = "Configura un objetivo · conversa con memoria · verifica la evidencia";
            lblSubtitulo.ForeColor = Color.FromArgb(192, 204, 232);
            lblSesion.Dock = DockStyle.Right;
            lblSesion.Width = 190;
            lblSesion.TextAlign = ContentAlignment.MiddleCenter;
            lblSesion.ForeColor = Color.FromArgb(133, 227, 195);
            lblSesion.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblSesion.Text = "SIN SESIÓN";
            bodyLayout.Dock = DockStyle.Fill;
            bodyLayout.ColumnCount = 2;
            bodyLayout.RowCount = 1;
            bodyLayout.Padding = new Padding(20, 16, 20, 10);
            bodyLayout.Margin = Padding.Empty;
            bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 328F));
            bodyLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            configPanel.Dock = DockStyle.Fill;
            configPanel.BackColor = Color.White;
            configPanel.Size = new Size(328, 636);
            configPanel.Margin = Padding.Empty;
            lblConfiguracion.Location = new Point(16, 16);
            lblConfiguracion.Size = new Size(294, 22);
            lblConfiguracion.ForeColor = Color.FromArgb(44, 57, 83);
            lblConfiguracion.Text = "01  CONFIGURAR AGENTE";
            lblConfiguracion.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblProveedor.Location = new Point(16, 52);
            lblProveedor.Size = new Size(140, 22);
            lblProveedor.ForeColor = Color.FromArgb(44, 57, 83);
            lblProveedor.Text = "Proveedor";
            cmbProveedor.Location = new Point(16, 74);
            cmbProveedor.Size = new Size(140, 25);
            cmbProveedor.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbProveedor.Items.AddRange(new object[] { "OpenAI", "Claude", "Gemini", "Grok" });
            lblModelo.Location = new Point(170, 52);
            lblModelo.Size = new Size(140, 22);
            lblModelo.ForeColor = Color.FromArgb(44, 57, 83);
            lblModelo.Text = "Modelo";
            txtModelo.Location = new Point(170, 74);
            txtModelo.Size = new Size(140, 25);
            txtModelo.BorderStyle = BorderStyle.FixedSingle;
            txtModelo.BackColor = Color.White;
            txtModelo.Text = "gpt-4o-mini";
            lblNombre.Location = new Point(16, 112);
            lblNombre.Size = new Size(294, 22);
            lblNombre.ForeColor = Color.FromArgb(44, 57, 83);
            lblNombre.Text = "Nombre del agente";
            txtNombre.Location = new Point(16, 134);
            txtNombre.Size = new Size(294, 25);
            txtNombre.BorderStyle = BorderStyle.FixedSingle;
            txtNombre.BackColor = Color.White;
            txtNombre.Text = "Aula · Organizador";
            lblProblema.Location = new Point(16, 174);
            lblProblema.Size = new Size(294, 22);
            lblProblema.ForeColor = Color.FromArgb(44, 57, 83);
            lblProblema.Text = "Problema que resolverá";
            txtProblema.Location = new Point(16, 196);
            txtProblema.Size = new Size(294, 80);
            txtProblema.BorderStyle = BorderStyle.FixedSingle;
            txtProblema.BackColor = Color.White;
            txtProblema.Text = "Los estudiantes tienen varias tareas y poco tiempo. Necesitan organizar el estudio según la prioridad de cada materia.";
            txtProblema.Multiline = true;
            txtProblema.ScrollBars = ScrollBars.Vertical;
            lblInstrucciones.Location = new Point(16, 290);
            lblInstrucciones.Size = new Size(294, 22);
            lblInstrucciones.ForeColor = Color.FromArgb(44, 57, 83);
            lblInstrucciones.Text = "Objetivo y reglas";
            txtInstrucciones.Location = new Point(16, 312);
            txtInstrucciones.Size = new Size(294, 178);
            txtInstrucciones.BorderStyle = BorderStyle.FixedSingle;
            txtInstrucciones.BackColor = Color.White;
            txtInstrucciones.Text = "Ayuda a organizar las tareas de estudio.\r\nPregunta cuánto tiempo tengo disponible.\r\nUsa las herramientas para conocer las tareas y calcular los minutos.\r\nExplica la propuesta con pasos breves y cita el resultado local.\r\nReconoce los límites del plan.";
            txtInstrucciones.Multiline = true;
            txtInstrucciones.ScrollBars = ScrollBars.Vertical;
            txtInstrucciones.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            btnCrear.Location = new Point(16, 510);
            btnCrear.Size = new Size(294, 36);
            btnCrear.FlatStyle = FlatStyle.Flat;
            btnCrear.BackColor = Color.FromArgb(70, 76, 166);
            btnCrear.ForeColor = Color.White;
            btnCrear.UseVisualStyleBackColor = false;
            btnCrear.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnCrear.Text = "Crear agente";
            btnCrear.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            btnNuevaSesion.Location = new Point(16, 554);
            btnNuevaSesion.Size = new Size(294, 36);
            btnNuevaSesion.FlatStyle = FlatStyle.Flat;
            btnNuevaSesion.BackColor = Color.White;
            btnNuevaSesion.ForeColor = Color.FromArgb(49, 62, 88);
            btnNuevaSesion.UseVisualStyleBackColor = false;
            btnNuevaSesion.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnNuevaSesion.Text = "Nueva sesión / configurar";
            btnNuevaSesion.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblClave.Location = new Point(16, 598);
            lblClave.Size = new Size(294, 34);
            lblClave.ForeColor = Color.FromArgb(44, 57, 83);
            lblClave.Text = "Clave: variable OPENAI_API_KEY";
            lblClave.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblClave.Font = new Font("Segoe UI", 8F);
            lblClave.ForeColor = Color.FromArgb(92, 105, 126);
            tabs.Dock = DockStyle.Fill;
            tabs.Margin = new Padding(16, 0, 0, 0);
            tabs.Size = new Size(736, 636);
            tabConversacion.BackColor = Color.White;
            tabConversacion.Padding = new Padding(12);
            tabConversacion.Size = new Size(728, 608);
            tabConversacion.Text = "02  Conversación";
            tabHerramienta.BackColor = Color.White;
            tabHerramienta.Padding = new Padding(12);
            tabHerramienta.Size = new Size(728, 608);
            tabHerramienta.Text = "03  Herramienta local";
            tabConsumo.BackColor = Color.White;
            tabConsumo.Padding = new Padding(12);
            tabConsumo.Size = new Size(728, 608);
            tabConsumo.Text = "04  Consumo";
            chatLayout.Dock = DockStyle.Fill;
            chatLayout.ColumnCount = 1;
            chatLayout.RowCount = 4;
            chatLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            chatLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            chatLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 112F));
            chatLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            lblChat.Dock = DockStyle.Fill;
            lblChat.ForeColor = Color.FromArgb(79, 94, 123);
            lblChat.Text = "La sesión recuerda los turnos. Revisa el resultado de las herramientas en la siguiente pestaña.";
            rtbConversacion.Dock = DockStyle.Fill;
            rtbConversacion.ReadOnly = true;
            rtbConversacion.BackColor = Color.FromArgb(248, 249, 253);
            rtbConversacion.BorderStyle = BorderStyle.None;
            rtbConversacion.Font = new Font("Segoe UI", 11F);
            rtbConversacion.DetectUrls = false;
            composer.Dock = DockStyle.Fill;
            composer.ColumnCount = 1;
            composer.RowCount = 2;
            composer.Margin = new Padding(0, 10, 0, 0);
            composer.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            composer.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            lblConsulta.Dock = DockStyle.Fill;
            lblConsulta.Text = "Tu consulta";
            txtConsulta.Dock = DockStyle.Fill;
            txtConsulta.Multiline = true;
            txtConsulta.ScrollBars = ScrollBars.Vertical;
            txtConsulta.MaxLength = 6000;
            txtConsulta.BorderStyle = BorderStyle.FixedSingle;
            txtConsulta.Font = new Font("Segoe UI", 10F);
            txtConsulta.Text = "Tengo 120 minutos para estudiar. Consulta mis tareas y calcula un plan con evidencia.";
            chatButtons.Dock = DockStyle.Fill;
            chatButtons.FlowDirection = FlowDirection.RightToLeft;
            chatButtons.WrapContents = false;
            chatButtons.Margin = Padding.Empty;
            btnEnviar.Location = new Point(0, 0);
            btnEnviar.Size = new Size(110, 34);
            btnEnviar.FlatStyle = FlatStyle.Flat;
            btnEnviar.BackColor = Color.FromArgb(70, 76, 166);
            btnEnviar.ForeColor = Color.White;
            btnEnviar.UseVisualStyleBackColor = false;
            btnEnviar.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnEnviar.Text = "Enviar";
            btnCancelar.Location = new Point(0, 0);
            btnCancelar.Size = new Size(105, 34);
            btnCancelar.FlatStyle = FlatStyle.Flat;
            btnCancelar.BackColor = Color.White;
            btnCancelar.ForeColor = Color.FromArgb(49, 62, 88);
            btnCancelar.UseVisualStyleBackColor = false;
            btnCancelar.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnCancelar.Text = "Cancelar";
            btnGuardar.Location = new Point(0, 0);
            btnGuardar.Size = new Size(145, 34);
            btnGuardar.FlatStyle = FlatStyle.Flat;
            btnGuardar.BackColor = Color.White;
            btnGuardar.ForeColor = Color.FromArgb(49, 62, 88);
            btnGuardar.UseVisualStyleBackColor = false;
            btnGuardar.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnGuardar.Text = "Guardar informe";
            lblToolInfo.Location = new Point(16, 16);
            lblToolInfo.Size = new Size(660, 52);
            lblToolInfo.ForeColor = Color.FromArgb(44, 57, 83);
            lblToolInfo.Text = "La herramienta reparte minutos según prioridades. Solo calcula en memoria: sin archivos, comandos ni envíos. Puedes probarla sin clave API.";
            dgvTareas.Location = new Point(16, 80);
            dgvTareas.Size = new Size(660, 180);
            dgvTareas.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            dgvTareas.AllowUserToAddRows = false;
            dgvTareas.AllowUserToDeleteRows = false;
            dgvTareas.AllowUserToResizeRows = false;
            dgvTareas.RowHeadersVisible = false;
            dgvTareas.BackgroundColor = Color.White;
            dgvTareas.BorderStyle = BorderStyle.FixedSingle;
            dgvTareas.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvTareas.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvTareas.MultiSelect = false;
            dgvTareas.EnableHeadersVisualStyles = false;
            dgvTareas.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(230, 234, 246);
            dgvTareas.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(46, 59, 87);
            dgvTareas.ColumnHeadersHeight = 32;
            dgvTareas.RowTemplate.Height = 30;
            dgvTareas.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 249, 252);
            colMateria.HeaderText = "Tarea / materia";
            colMateria.FillWeight = 75F;
            colMateria.MaxInputLength = 80;
            colMateria.SortMode = DataGridViewColumnSortMode.NotSortable;
            colPrioridad.HeaderText = "Prioridad (1–5)";
            colPrioridad.FillWeight = 25F;
            colPrioridad.MaxInputLength = 1;
            colPrioridad.SortMode = DataGridViewColumnSortMode.NotSortable;
            dgvTareas.Columns.AddRange(new DataGridViewColumn[] { colMateria, colPrioridad });
            btnAgregarTarea.Location = new Point(16, 274);
            btnAgregarTarea.Size = new Size(142, 36);
            btnAgregarTarea.FlatStyle = FlatStyle.Flat;
            btnAgregarTarea.BackColor = Color.White;
            btnAgregarTarea.ForeColor = Color.FromArgb(49, 62, 88);
            btnAgregarTarea.UseVisualStyleBackColor = false;
            btnAgregarTarea.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnAgregarTarea.Text = "Agregar tarea";
            btnQuitarTarea.Location = new Point(170, 274);
            btnQuitarTarea.Size = new Size(165, 36);
            btnQuitarTarea.FlatStyle = FlatStyle.Flat;
            btnQuitarTarea.BackColor = Color.White;
            btnQuitarTarea.ForeColor = Color.FromArgb(49, 62, 88);
            btnQuitarTarea.UseVisualStyleBackColor = false;
            btnQuitarTarea.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnQuitarTarea.Text = "Quitar seleccionada";
            lblMinutos.Location = new Point(16, 327);
            lblMinutos.Size = new Size(150, 22);
            lblMinutos.ForeColor = Color.FromArgb(44, 57, 83);
            lblMinutos.Text = "Minutos disponibles";
            nudMinutos.Location = new Point(170, 324);
            nudMinutos.Size = new Size(86, 25);
            nudMinutos.Minimum = 10M;
            nudMinutos.Maximum = 720M;
            nudMinutos.Value = 120M;
            btnProbarHerramienta.Location = new Point(274, 318);
            btnProbarHerramienta.Size = new Size(205, 36);
            btnProbarHerramienta.FlatStyle = FlatStyle.Flat;
            btnProbarHerramienta.BackColor = Color.FromArgb(70, 76, 166);
            btnProbarHerramienta.ForeColor = Color.White;
            btnProbarHerramienta.UseVisualStyleBackColor = false;
            btnProbarHerramienta.FlatAppearance.BorderColor = Color.FromArgb(210, 217, 231);
            btnProbarHerramienta.Text = "Probar cálculo local";
            lblHerramienta.Location = new Point(16, 371);
            lblHerramienta.Size = new Size(660, 24);
            lblHerramienta.ForeColor = Color.FromArgb(44, 57, 83);
            lblHerramienta.Text = "Sin ejecuciones locales todavía";
            txtEvidencia.Location = new Point(16, 404);
            txtEvidencia.Size = new Size(660, 183);
            txtEvidencia.BorderStyle = BorderStyle.FixedSingle;
            txtEvidencia.BackColor = Color.White;
            txtEvidencia.Text = "";
            txtEvidencia.Multiline = true;
            txtEvidencia.ScrollBars = ScrollBars.Vertical;
            txtEvidencia.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            txtEvidencia.ReadOnly = true;
            txtEvidencia.ScrollBars = ScrollBars.Both;
            txtEvidencia.WordWrap = false;
            txtEvidencia.Font = new Font("Consolas", 9F);
            lblConsumoInfo.Location = new Point(16, 16);
            lblConsumoInfo.Size = new Size(660, 60);
            lblConsumoInfo.ForeColor = Color.FromArgb(44, 57, 83);
            lblConsumoInfo.Text = "Consumo reportado por el proveedor y estimación del costo de la sesión.";
            lblTarifas.Location = new Point(16, 98);
            lblTarifas.Size = new Size(660, 26);
            lblTarifas.ForeColor = Color.FromArgb(44, 57, 83);
            lblTarifas.Text = "Tarifas del modelo · USD por millón de tokens";
            lblTarifas.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblEntrada.Location = new Point(16, 140);
            lblEntrada.Size = new Size(250, 22);
            lblEntrada.ForeColor = Color.FromArgb(44, 57, 83);
            lblEntrada.Text = "Entrada";
            lblSalida.Location = new Point(280, 140);
            lblSalida.Size = new Size(250, 22);
            lblSalida.ForeColor = Color.FromArgb(44, 57, 83);
            lblSalida.Text = "Salida";
            nudTarifaEntrada.Location = new Point(16, 164);
            nudTarifaEntrada.Size = new Size(180, 25);
            nudTarifaEntrada.DecimalPlaces = 4;
            nudTarifaEntrada.Maximum = 1000M;
            nudTarifaEntrada.Increment = 0.05M;
            nudTarifaSalida.Location = new Point(280, 164);
            nudTarifaSalida.Size = new Size(180, 25);
            nudTarifaSalida.DecimalPlaces = 4;
            nudTarifaSalida.Maximum = 1000M;
            nudTarifaSalida.Increment = 0.05M;
            lblTokens.Location = new Point(16, 214);
            lblTokens.Size = new Size(660, 24);
            lblTokens.ForeColor = Color.FromArgb(44, 57, 83);
            lblTokens.Text = "Tokens reportados: 0 entrada / 0 salida";
            lblCosto.Location = new Point(16, 244);
            lblCosto.Size = new Size(660, 44);
            lblCosto.ForeColor = Color.FromArgb(44, 57, 83);
            lblCosto.Text = "Estimación: USD 0.000000";
            lblCosto.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblCostNote.Location = new Point(16, 296);
            lblCostNote.Size = new Size(660, 68);
            lblCostNote.ForeColor = Color.FromArgb(44, 57, 83);
            lblCostNote.Text = "Estimación sobre el uso reportado y las tarifas que ingreses. No descuenta caché ni incluye cargos adicionales. Si falla una consulta, el costo puede ser mayor al mostrado. Para otros modelos debes ingresar su tarifa.";
            lblEstado.Dock = DockStyle.Fill;
            lblEstado.Padding = new Padding(20, 0, 0, 0);
            lblEstado.TextAlign = ContentAlignment.MiddleLeft;
            lblEstado.ForeColor = Color.FromArgb(71, 88, 116);
            lblEstado.Text = "Listo. Revisa la configuración y crea el agente; también puedes probar la herramienta sin conexión.";
            this.Controls.Add(rootLayout);
            rootLayout.Controls.Add(headerPanel);
            headerPanel.Controls.Add(lblTitulo);
            headerPanel.Controls.Add(lblSubtitulo);
            headerPanel.Controls.Add(lblSesion);
            rootLayout.Controls.Add(bodyLayout);
            bodyLayout.Controls.Add(configPanel);
            configPanel.Controls.Add(lblConfiguracion);
            configPanel.Controls.Add(lblProveedor);
            configPanel.Controls.Add(cmbProveedor);
            configPanel.Controls.Add(lblModelo);
            configPanel.Controls.Add(txtModelo);
            configPanel.Controls.Add(lblNombre);
            configPanel.Controls.Add(txtNombre);
            configPanel.Controls.Add(lblProblema);
            configPanel.Controls.Add(txtProblema);
            configPanel.Controls.Add(lblInstrucciones);
            configPanel.Controls.Add(txtInstrucciones);
            configPanel.Controls.Add(btnCrear);
            configPanel.Controls.Add(btnNuevaSesion);
            configPanel.Controls.Add(lblClave);
            bodyLayout.Controls.Add(tabs);
            tabs.Controls.Add(tabConversacion);
            tabs.Controls.Add(tabHerramienta);
            tabs.Controls.Add(tabConsumo);
            tabConversacion.Controls.Add(chatLayout);
            chatLayout.Controls.Add(lblChat);
            chatLayout.Controls.Add(rtbConversacion);
            chatLayout.Controls.Add(composer);
            composer.Controls.Add(lblConsulta);
            composer.Controls.Add(txtConsulta);
            chatLayout.Controls.Add(chatButtons);
            chatButtons.Controls.Add(btnEnviar);
            chatButtons.Controls.Add(btnCancelar);
            chatButtons.Controls.Add(btnGuardar);
            tabHerramienta.Controls.Add(lblToolInfo);
            tabHerramienta.Controls.Add(dgvTareas);
            tabHerramienta.Controls.Add(btnAgregarTarea);
            tabHerramienta.Controls.Add(btnQuitarTarea);
            tabHerramienta.Controls.Add(lblMinutos);
            tabHerramienta.Controls.Add(nudMinutos);
            tabHerramienta.Controls.Add(btnProbarHerramienta);
            tabHerramienta.Controls.Add(lblHerramienta);
            tabHerramienta.Controls.Add(txtEvidencia);
            tabConsumo.Controls.Add(lblConsumoInfo);
            tabConsumo.Controls.Add(lblTarifas);
            tabConsumo.Controls.Add(lblEntrada);
            tabConsumo.Controls.Add(lblSalida);
            tabConsumo.Controls.Add(nudTarifaEntrada);
            tabConsumo.Controls.Add(nudTarifaSalida);
            tabConsumo.Controls.Add(lblTokens);
            tabConsumo.Controls.Add(lblCosto);
            tabConsumo.Controls.Add(lblCostNote);
            rootLayout.Controls.Add(lblEstado);
            cmbProveedor.SelectedIndexChanged += cmbProveedor_SelectedIndexChanged;
            btnCrear.Click += btnCrear_Click;
            btnNuevaSesion.Click += btnNuevaSesion_Click;
            btnEnviar.Click += btnEnviar_Click;
            btnCancelar.Click += btnCancelar_Click;
            btnGuardar.Click += btnGuardar_Click;
            btnAgregarTarea.Click += btnAgregarTarea_Click;
            btnQuitarTarea.Click += btnQuitarTarea_Click;
            btnProbarHerramienta.Click += btnProbarHerramienta_Click;
            nudTarifaEntrada.ValueChanged += tarifas_ValueChanged;
            nudTarifaSalida.ValueChanged += tarifas_ValueChanged;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(239, 242, 249);
            ClientSize = new Size(1120, 780);
            Font = new Font("Segoe UI", 9F);
            MinimumSize = new Size(1000, 660);
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Aula · Agente con objetivo, memoria y herramientas";
            WindowState = FormWindowState.Maximized;
            ((System.ComponentModel.ISupportInitialize)dgvTareas).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudMinutos).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudTarifaEntrada).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudTarifaSalida).EndInit();
            rootLayout.ResumeLayout(false);
            rootLayout.PerformLayout();
            headerPanel.ResumeLayout(false);
            headerPanel.PerformLayout();
            bodyLayout.ResumeLayout(false);
            bodyLayout.PerformLayout();
            configPanel.ResumeLayout(false);
            configPanel.PerformLayout();
            tabs.ResumeLayout(false);
            tabs.PerformLayout();
            tabConversacion.ResumeLayout(false);
            tabConversacion.PerformLayout();
            tabHerramienta.ResumeLayout(false);
            tabHerramienta.PerformLayout();
            tabConsumo.ResumeLayout(false);
            tabConsumo.PerformLayout();
            chatLayout.ResumeLayout(false);
            chatLayout.PerformLayout();
            composer.ResumeLayout(false);
            composer.PerformLayout();
            chatButtons.ResumeLayout(false);
            chatButtons.PerformLayout();
            ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.Panel headerPanel;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblSubtitulo;
        private System.Windows.Forms.Label lblSesion;
        private System.Windows.Forms.TableLayoutPanel bodyLayout;
        private System.Windows.Forms.Panel configPanel;
        private System.Windows.Forms.Label lblConfiguracion;
        private System.Windows.Forms.Label lblProveedor;
        private System.Windows.Forms.ComboBox cmbProveedor;
        private System.Windows.Forms.Label lblModelo;
        private System.Windows.Forms.TextBox txtModelo;
        private System.Windows.Forms.Label lblNombre;
        private System.Windows.Forms.TextBox txtNombre;
        private System.Windows.Forms.Label lblProblema;
        private System.Windows.Forms.TextBox txtProblema;
        private System.Windows.Forms.Label lblInstrucciones;
        private System.Windows.Forms.TextBox txtInstrucciones;
        private System.Windows.Forms.Button btnCrear;
        private System.Windows.Forms.Button btnNuevaSesion;
        private System.Windows.Forms.Label lblClave;
        private System.Windows.Forms.TabControl tabs;
        private System.Windows.Forms.TabPage tabConversacion;
        private System.Windows.Forms.TabPage tabHerramienta;
        private System.Windows.Forms.TabPage tabConsumo;
        private System.Windows.Forms.TableLayoutPanel chatLayout;
        private System.Windows.Forms.Label lblChat;
        private System.Windows.Forms.RichTextBox rtbConversacion;
        private System.Windows.Forms.TableLayoutPanel composer;
        private System.Windows.Forms.Label lblConsulta;
        private System.Windows.Forms.TextBox txtConsulta;
        private System.Windows.Forms.FlowLayoutPanel chatButtons;
        private System.Windows.Forms.Button btnEnviar;
        private System.Windows.Forms.Button btnCancelar;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Label lblToolInfo;
        private System.Windows.Forms.DataGridView dgvTareas;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMateria;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPrioridad;
        private System.Windows.Forms.Button btnAgregarTarea;
        private System.Windows.Forms.Button btnQuitarTarea;
        private System.Windows.Forms.Label lblMinutos;
        private System.Windows.Forms.NumericUpDown nudMinutos;
        private System.Windows.Forms.Button btnProbarHerramienta;
        private System.Windows.Forms.Label lblHerramienta;
        private System.Windows.Forms.TextBox txtEvidencia;
        private System.Windows.Forms.Label lblConsumoInfo;
        private System.Windows.Forms.Label lblTarifas;
        private System.Windows.Forms.Label lblEntrada;
        private System.Windows.Forms.Label lblSalida;
        private System.Windows.Forms.NumericUpDown nudTarifaEntrada;
        private System.Windows.Forms.NumericUpDown nudTarifaSalida;
        private System.Windows.Forms.Label lblTokens;
        private System.Windows.Forms.Label lblCosto;
        private System.Windows.Forms.Label lblCostNote;
        private System.Windows.Forms.Label lblEstado;
    }
}
